export const FALLBACK_MENUS = [
  {
    "_id": "6a7eee832e36bbf82f505a90",
    "isTopLevel": true,
    "category": "home",
    "__v": 0,
    "isActive": true,
    "order": 1,
    "title": "Home",
    "url": "/",
    "icon": ""
  },
  {
    "_id": "6a7ee9603ac57da1f2b018eb",
    "title": "Kundli Reading",
    "url": "/kundli",
    "category": "astrology",
    "group": "General",
    "order": 1,
    "isActive": true,
    "__v": 0,
    "icon": "🔮"
  },
  {
    "_id": "6a7ee9603ac57da1f2b018ee",
    "title": "Daily Horoscope",
    "url": "/horoscope/daily",
    "category": "horoscope",
    "group": "Time-Based Forecasts",
    "order": 1,
    "isActive": true,
    "__v": 0,
    "icon": "⭐"
  },
  {
    "_id": "6a7ee9603ac57da1f2b018f0",
    "title": "Kundali Generator",
    "url": "/kundli",
    "category": "tools",
    "group": "General",
    "order": 1,
    "isActive": true,
    "__v": 0,
    "icon": "🔮"
  },
  {
    "_id": "6a7ee9603ac57da1f2b01906",
    "title": "WhatsApp Us",
    "url": "#",
    "category": "consult",
    "group": "General",
    "order": 1,
    "isActive": true,
    "__v": 0,
    "icon": "<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"#dcfce7\" stroke=\"#22c55e\" strokeWidth=\"2\" strokeLinecap=\"round\" strokeLinejoin=\"round\"><path d=\"M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z\"/></svg>"
  },
  {
    "_id": "6a7ee9603ac57da1f2b0190a",
    "title": "Read Blog",
    "url": "#!",
    "category": "knowledge",
    "group": "General",
    "order": 1,
    "isActive": true,
    "__v": 0,
    "icon": "📰"
  },
  {
    "_id": "6a7eee832e36bbf82f505a91",
    "isTopLevel": true,
    "category": "horoscope",
    "__v": 0,
    "isActive": true,
    "order": 2,
    "title": "Horoscope",
    "url": "/horoscope",
    "icon": ""
  },
  {
    "_id": "6a7ee9603ac57da1f2b018ef",
    "title": "Tomorrow's Horoscope",
    "url": "/horoscope/tomorrow",
    "category": "horoscope",
    "group": "Time-Based Forecasts",
    "order": 2,
    "isActive": true,
    "__v": 0,
    "icon": "🔭"
  },
  {
    "_id": "6a7ee9603ac57da1f2b018ec",
    "title": "Numerology Reading",
    "url": "/numerology",
    "category": "astrology",
    "group": "General",
    "order": 2,
    "isActive": true,
    "__v": 0,
    "icon": "🔢"
  },
  {
    "_id": "6a7ee9603ac57da1f2b01907",
    "title": "WhatsApp Us",
    "url": "#",
    "category": "consult",
    "group": "General",
    "order": 2,
    "isActive": true,
    "__v": 0,
    "icon": "<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"#dbeafe\" stroke=\"#3b82f6\" strokeWidth=\"2\" strokeLinecap=\"round\" strokeLinejoin=\"round\"><path d=\"M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z\"/></svg>"
  },
  {
    "_id": "6a7ee9603ac57da1f2b0190b",
    "title": "Vedic Astrology FAQ",
    "url": "/faq",
    "category": "knowledge",
    "group": "General",
    "order": 2,
    "isActive": true,
    "__v": 0,
    "icon": "💬"
  },
  {
    "_id": "6a7eee832e36bbf82f505a92",
    "isTopLevel": true,
    "category": "tools",
    "__v": 0,
    "isActive": true,
    "order": 3,
    "title": "Free Astrology Tools",
    "url": "/astrology-calculators",
    "icon": ""
  },
  {
    "_id": "6a7ee9603ac57da1f2b018fc",
    "title": "Weekly Horoscope",
    "url": "/horoscope/weekly",
    "category": "horoscope",
    "group": "Time-Based Forecasts",
    "order": 3,
    "isActive": true,
    "__v": 0,
    "icon": "<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"#e0e7ff\" stroke=\"#6366f1\" strokeWidth=\"2\" strokeLinecap=\"round\" strokeLinejoin=\"round\"><rect width=\"18\" height=\"18\" x=\"3\" y=\"4\" rx=\"2\" ry=\"2\"/><line x1=\"16\" x2=\"16\" y1=\"2\" y2=\"6\"/><line x1=\"8\" x2=\"8\" y1=\"2\" y2=\"6\"/><line x1=\"3\" x2=\"21\" y1=\"10\" y2=\"10\"/><path d=\"M8 14h.01\"/><path d=\"M12 14h.01\"/><path d=\"M16 14h.01\"/><path d=\"M8 18h.01\"/><path d=\"M12 18h.01\"/><path d=\"M16 18h.01\"/></svg>"
  },
  {
    "_id": "6a7ee9603ac57da1f2b018ed",
    "title": "Tarot Reading",
    "url": "/tarot",
    "category": "astrology",
    "group": "General",
    "order": 3,
    "isActive": true,
    "__v": 0,
    "icon": "⭐"
  },
  {
    "_id": "6a7ee9603ac57da1f2b01908",
    "title": "Chat with AI Astrologer",
    "url": "#?mode=chat",
    "category": "consult",
    "group": "General",
    "order": 3,
    "isActive": true,
    "__v": 0,
    "icon": "<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"#cffafe\" stroke=\"#06b6d4\" strokeWidth=\"2\" strokeLinecap=\"round\" strokeLinejoin=\"round\"><path d=\"M12 8V4H8\"/><rect width=\"16\" height=\"12\" x=\"4\" y=\"8\" rx=\"2\"/><path d=\"M2 14h2\"/><path d=\"M20 14h2\"/><path d=\"M15 13v2\"/><path d=\"M9 13v2\"/></svg>"
  },
  {
    "_id": "6a7ee9603ac57da1f2b0190c",
    "title": "Astrology Articles",
    "url": "/articles",
    "category": "knowledge",
    "group": "General",
    "order": 3,
    "isActive": true,
    "__v": 0,
    "icon": "📰"
  },
  {
    "_id": "6a7eee832e36bbf82f505a901",
    "isTopLevel": true,
    "category": "kundli",
    "__v": 0,
    "isActive": true,
    "order": 4,
    "title": "Kundli & Reports",
    "url": "/kundli",
    "icon": ""
  },
  {
    "_id": "6a7ee9603ac57da1f2b0190d",
    "title": "Festivals",
    "url": "/festivals",
    "category": "knowledge",
    "group": "General",
    "order": 4,
    "isActive": true,
    "__v": 0,
    "icon": "🎉"
  },
  {
    "_id": "6a7ee9603ac57da1f2b01900",
    "title": "Monthly Horoscope",
    "url": "/horoscope/monthly",
    "category": "horoscope",
    "group": "Time-Based Forecasts",
    "order": 4,
    "isActive": true,
    "__v": 0,
    "icon": "🌕"
  },
  {
    "_id": "6a7ee9603ac57da1f2b018f1",
    "title": "Rashi Calculator",
    "url": "/rashi-calculator",
    "category": "tools",
    "group": "General",
    "order": 4,
    "isActive": true,
    "__v": 0,
    "icon": "🧿"
  },
  {
    "_id": "6a7ee9603ac57da1f2b01909",
    "title": "Talk with AI Astrologer",
    "url": "#?mode=call",
    "category": "consult",
    "group": "General",
    "order": 4,
    "isActive": true,
    "__v": 0,
    "icon": "<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"#f3e8ff\" stroke=\"#a855f7\" strokeWidth=\"2\" strokeLinecap=\"round\" strokeLinejoin=\"round\"><path d=\"M3 18v-6a9 9 0 0 1 18 0v6\"/><path d=\"M21 19a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3zM3 19a2 2 0 0 0 2 2h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H3z\"/></svg>"
  },
  {
    "_id": "6a7eee832e36bbf82f505a93",
    "isTopLevel": true,
    "category": "consult",
    "__v": 0,
    "isActive": true,
    "order": 5,
    "title": "Consult an Astrologer",
    "url": "#",
    "icon": ""
  },
  {
    "_id": "6a7ee9603ac57da1f2b0190e",
    "title": "Celebrity Horoscope",
    "url": "/celebrity-horoscopes",
    "category": "knowledge",
    "group": "General",
    "order": 5,
    "isActive": true,
    "__v": 0,
    "icon": "👑"
  },
  {
    "_id": "6a7ee9603ac57da1f2b018f2",
    "title": "Numerology",
    "url": "/numerology",
    "category": "tools",
    "group": "General",
    "order": 5,
    "isActive": true,
    "__v": 0,
    "icon": "🔢"
  },
  {
    "_id": "6a7ee9603ac57da1f2b01901",
    "title": "Yearly Horoscope",
    "url": "/horoscope/yearly",
    "category": "horoscope",
    "group": "Time-Based Forecasts",
    "order": 5,
    "isActive": true,
    "__v": 0,
    "icon": "🪐"
  },
  {
    "_id": "6a7ee9603ac57da1f2b018f3",
    "title": "Love Compatibility",
    "url": "/compatibility",
    "category": "tools",
    "group": "General",
    "order": 6,
    "isActive": true,
    "__v": 0,
    "icon": "💖"
  },
  {
    "_id": "6a7eee832e36bbf82f505a94",
    "category": "pujas",
    "isTopLevel": true,
    "__v": 0,
    "isActive": true,
    "order": 6,
    "title": "Book a Remedy Puja",
    "url": "/book-a-puja",
    "icon": ""
  },

  {
    "_id": "6a7ee9603ac57da1f2b01902",
    "title": "Horoscope Matching",
    "url": "/horoscope-matching",
    "category": "horoscope",
    "group": "Specialty Horoscopes",
    "order": 6,
    "isActive": true,
    "__v": 0,
    "icon": "💖"
  },
  {
    "_id": "6a7ee9603ac57da1f2b0190f",
    "title": "Healings",
    "url": "/healing",
    "category": "knowledge",
    "group": "General",
    "order": 6,
    "isActive": true,
    "__v": 0,
    "icon": "🌿"
  },
  {
    "_id": "6a7ee9603ac57da1f2b018f4",
    "title": "Lal Kitab Reading",
    "url": "/lal-kitab",
    "category": "tools",
    "group": "General",
    "order": 7,
    "isActive": true,
    "__v": 0,
    "icon": "📕"
  },
  {
    "_id": "6a7eee832e36bbf82f505a96",
    "isTopLevel": true,
    "category": "knowledge",
    "__v": 0,
    "isActive": true,
    "order": 7,
    "title": "Knowledge Center",
    "url": "/knowledge",
    "icon": ""
  },
  {
    "_id": "6a7ee9603ac57da1f2b01910",
    "title": "Matrimony",
    "url": "/matrimony",
    "category": "knowledge",
    "group": "General",
    "order": 7,
    "isActive": true,
    "__v": 0,
    "icon": "💞"
  },
  {
    "_id": "6a7ee9603ac57da1f2b01903",
    "title": "Love Horoscope",
    "url": "/love-horoscope",
    "category": "horoscope",
    "group": "Specialty Horoscopes",
    "order": 7,
    "isActive": true,
    "__v": 0,
    "icon": "💖"
  },
  {
    "_id": "6a7ee9603ac57da1f2b018f5",
    "title": "Atlas / Location Finder",
    "url": "/atlas",
    "category": "tools",
    "group": "General",
    "order": 8,
    "isActive": true,
    "__v": 0,
    "icon": "🗺️"
  },
  {
    "_id": "6a7ee9603ac57da1f2b01911",
    "title": "Learn Astrology",
    "url": "/learn",
    "category": "knowledge",
    "group": "General",
    "order": 8,
    "isActive": true,
    "__v": 0,
    "icon": "📚"
  },
  {
    "_id": "6a7ee9603ac57da1f2b01904",
    "title": "Chinese Horoscope",
    "url": "/chinese-horoscope",
    "category": "horoscope",
    "group": "Specialty Horoscopes",
    "order": 8,
    "isActive": true,
    "__v": 0,
    "icon": "🐉"
  },
  {
    "_id": "6a7eee832e36bbf82f505a95",
    "isTopLevel": true,
    "category": "shop",
    "__v": 0,
    "isActive": true,
    "order": 8,
    "title": "Shop",
    "url": "/shop",
    "icon": ""
  },
  {
    "_id": "6a7ee9603ac57da1f2b018f6",
    "title": "Panchang Today",
    "url": "/panchang",
    "category": "tools",
    "group": "General",
    "order": 9,
    "isActive": true,
    "__v": 0,
    "icon": "<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"#fef08a\" stroke=\"#eab308\" strokeWidth=\"2\" strokeLinecap=\"round\" strokeLinejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"4\"/><path d=\"M12 2v2\"/><path d=\"M12 20v2\"/><path d=\"m4.93 4.93 1.41 1.41\"/><path d=\"m17.66 17.66 1.41 1.41\"/><path d=\"M2 12h2\"/><path d=\"M20 12h2\"/><path d=\"m6.34 17.66-1.41 1.41\"/><path d=\"m19.07 4.93-1.41 1.41\"/></svg>"
  },
  {
    "_id": "6a7ee9603ac57da1f2b01905",
    "title": "Celebrity Horoscope",
    "url": "/celebrity-horoscopes",
    "category": "horoscope",
    "group": "Specialty Horoscopes",
    "order": 9,
    "isActive": true,
    "__v": 0,
    "icon": "👑"
  },
  {
    "_id": "6a7ee9603ac57da1f2b018f7",
    "title": "Rahu Kaal Today",
    "url": "/rahu-kaal",
    "category": "tools",
    "group": "General",
    "order": 10,
    "isActive": true,
    "__v": 0,
    "icon": "<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"#fef08a\" stroke=\"#eab308\" strokeWidth=\"2\" strokeLinecap=\"round\" strokeLinejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"4\"/><path d=\"M12 2v2\"/><path d=\"M12 20v2\"/><path d=\"m4.93 4.93 1.41 1.41\"/><path d=\"m17.66 17.66 1.41 1.41\"/><path d=\"M2 12h2\"/><path d=\"M20 12h2\"/><path d=\"m6.34 17.66-1.41 1.41\"/><path d=\"m19.07 4.93-1.41 1.41\"/></svg>"
  },
  {
    "_id": "6a7ee9603ac57da1f2b018f8",
    "title": "Muhurat Finder",
    "url": "/muhurat",
    "category": "tools",
    "group": "General",
    "order": 11,
    "isActive": true,
    "__v": 0,
    "icon": "🔔"
  },
  {
    "_id": "6a7ee9603ac57da1f2b018f9",
    "title": "Baby Names",
    "url": "/baby-names",
    "category": "tools",
    "group": "General",
    "order": 12,
    "isActive": true,
    "__v": 0,
    "icon": "👶"
  },
  {
    "_id": "6a7ee9603ac57da1f2b018fa",
    "title": "Chinese Horoscope",
    "url": "/chinese-horoscope",
    "category": "tools",
    "group": "General",
    "order": 13,
    "isActive": true,
    "__v": 0,
    "icon": "🐉"
  },
  {
    "_id": "6a7ee9603ac57da1f2b018fb",
    "title": "Festivals Calendar",
    "url": "/festivals",
    "category": "tools",
    "group": "General",
    "order": 14,
    "isActive": true,
    "__v": 0,
    "icon": "🎉"
  },
  {
    "_id": "6a7ee9603ac57da1f2b018fcf",
    "title": "Astrology Calendar",
    "url": "/calendar",
    "category": "tools",
    "group": "General",
    "order": 15,
    "isActive": true,
    "__v": 0,
    "icon": "⭐"
  }
];
export const FALLBACK_PUJAS = [
  { _id: 'p1', title: 'Rudrabhishek Puja', slug: 'rudrabhishek' },
  { _id: 'p2', title: 'Job Attract & Confirm Puja', slug: 'job-attract-confirm-puja' },
  { _id: 'p3', title: 'Money Attract Puja (Dhan Laxmi Puja)', slug: 'dhan-laxmi-puja' },
  { _id: 'p4', title: 'Ganesh Ji Ko Laddoo Arpan', slug: 'ganesh-ji-ko-laddoo-arpan' },
  { _id: 'p5', title: 'Love / Marriage Healing', slug: 'love-marriage-healing' },
  { _id: 'p6', title: 'Commitment Spell', slug: 'commitment-spell' },
  { _id: 'p7', title: 'Mangal Dosh Nivaran Puja', slug: 'mangal-dosh-nivaran-puja' },
  { _id: 'p8', title: 'Attract Your Love Spell', slug: 'attract-your-love-spell' },
  { _id: 'p9', title: 'Hanuman Sindoor / Boondi Puja', slug: 'hanuman-sindoor-boondi-arpan' },
  { _id: 'p10', title: 'Vishnu Sahasranamam', slug: 'vishnu-sahasranamam-puja' },
  { _id: 'p11', title: 'Shani Tel Arpan and Aarti', slug: 'shani-tel-arpan-aarti' },
  { _id: 'p12', title: 'Rahu Ketu Grah Shanti Puja', slug: 'rahu-ketu-grah-shanti-puja' }
];
